### ISSUE TITLE
Warrior Fury Titan's Grip Detection fails after Spec change

### ISSUE THREAD

**Issue by Cephel** [cdmichaelb/Outfitter#119] opened 2022-10-27 06:57 UTC
It seems that the mechanic that was added to detect Titan's Grip only runs once when the addon is loaded, so it cannot handle dualspec.

This works:
1. Respec to Fury (with TG)
2. Log out
3. Log back in
4. Equip Fury set

This also works:
1. Respec to Fury (with TG)
2. Reload UI
3. Equip Fury set

This doesn't work:
1. Respec to Fury (with TG)
2. Equip Fury set

The solution would seem to run the TG detection after a spec change, in addition to on-load.

Likely a duplicate of #116

**Comment by Gogo1951** [comment] 2022-11-27 15:20
Dupe of #116

**Closed as completed by Gogo1951** 2022-11-27 15:20 UTC
